language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

services:
  - docker

defore_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
